argoWorkflow:
  s3:
    bucket: devtron-pro-ci-logs
    keyFormat: demo-v1/{{workflow.name}}
    region: us-east-2
  containerRuntimeExecutor: pns
  replicas: 1
  labels: {}
  annotations: {}
  EnvVariables: []
  EnvVariablesFrom: []
  workflowController:
    args:
      execImage: quay.io/argoproj/argoexec:v3.4.7
      # if you making disableIMDSv1 as true please use the below image or latest tag one
      # execImage: quay.io/argoproj/argoexec:v3.4.3
    image: quay.io/argoproj/workflow-controller:v3.4.7
    # image: quay.io/argoproj/workflow-controller:v3.4.3
    resources:
      limits:
        cpu: "0.3"
        memory: 300Mi
      requests:
        cpu: "0.03"
        memory: 50Mi
  executor:
    imagePullPolicy: IfNotPresent


disableIMDSv1: false
