argoWorkflow:
  s3:
    bucket: devtron-pro-ci-logs
    keyFormat: demo-v1/{{workflow.name}}
    region: us-east-2
  workflowController:
    image: quay.io/argoproj/workflow-controller:v3.0.7
    replicas: 1
    resources:
      limits:
        cpu: "0.3"
        memory: 300Mi
      requests:
        cpu: "0.03"
        memory: 50Mi
  executor:
    imagePullPolicy: IfNotPresent
