{{- range .Values.service_account_external.namespaces }}
apiVersion: v1
metadata:
  annotations: {}
  name: dt-logs-s3-credentials
  namespace: {{ . }}
data:
  accessKey: {{ $.Values.accesskey }}
  secretKey: {{ $.Values.secretkey }}
kind: Secret
---
{{- end }}