{{- range .Values.execute_in_application_env.namespaces }}
apiVersion: v1
metadata:
  annotations: {}
  name: dt-logs-s3-credentials
  namespace: {{ . }}
data:
  accessKey: {{ $.Values.execute_in_application_env.accesskey }}
  secretKey: {{ $.Values.execute_in_application_env.secretkey }}
kind: Secret
---
{{- end }}