apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: devtroncd
---
{{- range .Values.service_account_external.namespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd-runner
  namespace: {{ . }}
---
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.kubewatch.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: kubewatch
  namespace: devtroncd