name: winter-soldier
description: Helm chart to deploy winter-soldier helm chart which is use for clean up and reduce k8s workloads according to user defined time of the day and conditions.
version: 0.10.0
apiVersion: v1
appVersion: 0.1.0
maintainers:
- email: ajay@devtron.ai
  name: Ajay
