apiVersion: v1
items:
- apiVersion: v1
  data:
    config: |
      parallelism: 50
      artifactRepository:
        # archiveLogs will archive the main container logs as an artifact
        archiveLogs: true
        s3:
          endpoint: s3.amazonaws.com
{{ toYaml .Values.argoWorkflow.s3 | indent 10 }}
     {{- if not $.Values.disableIMDSv1 }}
      containerRuntimeExecutor: {{ $.Values.argoWorkflow.containerRuntimeExecutor }}
      {{- end }}
      executor:
{{ toYaml .Values.argoWorkflow.executor | indent 8 }}
  kind: ConfigMap
  metadata:
    name: workflow-controller-configmap
    namespace: {{ .Release.Namespace }}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
