apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  {{- if and $.Values.argoWorkflow $.Values.argoWorkflow.annotations }}
  annotations:
{{- toYaml $.Values.argoWorkflow.annotations | nindent 4 }}
  {{- end }}
  {{- if and $.Values.argoWorkflow $.Values.argoWorkflow.labels }}
  labels:
{{- toYaml $.Values.argoWorkflow.labels | nindent 4 }}      
  {{- end }}
spec:
  {{- if and $.Values.argoWorkflow $.Values.argoWorkflow.replicas }}
  replicas: {{ $.Values.argoWorkflow.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
        {{- if and $.Values.argoWorkflow $.Values.argoWorkflow.labels }}
{{- toYaml $.Values.argoWorkflow.labels | nindent 8 }}      
        {{- end }}
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - quay.io/argoproj/argoexec:v3.0.7
        command:
        - workflow-controller
        env:
          - name: LEADER_ELECTION_IDENTITY
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
         {{- if and $.Values.argoWorkflow $.Values.argoWorkflow.EnvVariables }}
{{ toYaml $.Values.argoWorkflow.EnvVariables | indent 10 }}
         {{- end }}
        resources:
{{ toYaml .Values.argoWorkflow.workflowController.resources | indent 10 }}
        image: {{ .Values.argoWorkflow.workflowController.image }}
        name: workflow-controller
      serviceAccountName: argo