name: in-clustercd
description: Helm chart to deploy in-clustercd to run pre and post deployment in application environments.
version: 0.10.0
appVersion: 0.1.0
apiVersion: v1
maintainers:
- email: devops@devtron.ai
  name: Devtron Devops Team
- email: ajay@devtron.ai
  name: Ajay